name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-semantic-release build

    - name: Configure git
      run: |
        git config --global user.name "semantic-release"
        git config --global user.email "semantic-release@github.com"

    - name: Python Semantic Release
      id: release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        semantic-release publish --verbosity=DEBUG

    - name: Upload to PyPI (if enabled)
      if: steps.release.outputs.released == 'true' && false
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        pip install twine
        twine upload dist/*

    - name: Publish release summary
      if: steps.release.outputs.released == 'true'
      run: |
        echo "Released version: ${{ steps.release.outputs.version }}"
        echo "Release notes: ${{ steps.release.outputs.release_notes }}"